### ISSUE TITLE
terraform orchestration support

### ISSUE THREAD

**Issue by avelino** [gofn/gofn#83]
ref #54 

is writter in Go https://github.com/hashicorp/terraform

Idea:

change `github.com/gofn/gofn/iaas/digitalocean` by terraform digitalocean provider[1]

Create `adapters` (`github.com/gofn/gofn/iaas/digitalocean`) to terraform providers

[1] https://github.com/terraform-providers/terraform-provider-digitalocean

**Comment by Horaddrim** [comment]
The idea is to make Terraform create the functions?

**Comment by avelino** [comment]
change `github.com/gofn/gofn/iaas/digitalocean` by terraform digitalocean provider[1]

Create `adapters` (`github.com/gofn/gofn/iaas/digitalocean`) to terraform providers

[1] https://github.com/terraform-providers/terraform-provider-digitalocean

**Comment by avelino** [comment]
Upgrade issue description

**Comment by gtsalles** [comment]
On it.

**Comment by gtsalles** [comment]
I mean, we could to this steps via code, but I think that the purpose of using terraform is to remove the direct calls to the provider APIs.

**Comment by avelino** [comment]
@gtsalles 
On terraform used

```
variable "do_token" {}
variable "pub_key" {}
variable "pvt_key" {}
variable "ssh_fingerprint" {}

provider "digitalocean" {
  token = "${var.do_token}"
}
```
to define auth on cloud, with that we don't have to worry about creating the key, TerraForm manages it

**Comment by gtsalles** [comment]
@avelino yes, how to use the keys is clear to me, what it isn't is how we integrate terraform in the way the process is defined today.
Now, we check for existing ssh keys on DO, and create a new one (when it doesn't exist), then upload it to the account. With terraform we can't make this check for existing keys. We can't assume that we always will have a key in there, neither create a new one for every machine creation.

**Comment by gtsalles** [comment]
After some research[1], I came to the conclusion that for now, it'll be too much work to get to a working solution for using terraform as a package.
As answered to me [2] in the terraform mail list, it would be easier to make shell calls in the code, and I don't think that's the more suitable solution for this. I think we can close this for now.

[1] https://github.com/hashicorp/terraform/issues/17904
[2] https://groups.google.com/forum/#msg/terraform-tool/7clPX0J7FmU/OqL1lcuWCwAJ
