### ISSUE TITLE
UUID returning multi-value

### ISSUE THREAD

**Issue by rogeriozambon** [gofn/gofn#98]
When I tried to install `gofn`, an error was returned by the `uuid` [(satori/go.uuid)](https://github.com/satori/go.uuid/blob/master/generator.go#L68) dependency.

```bash
$ go get -u github.com/gofn/gofn
# github.com/gofn/gofn/provision
gofn/gofn/provision/docker.go:82:48: multiple-value uuid.NewV4() in single-value context
```

And the problem affects the following parts:
- https://github.com/gofn/gofn/blob/master/provision/docker.go#L82
- https://github.com/gofn/gofn/blob/master/iaas/digitalocean/digitalocean.go#L200

I can create a pull request to fix this.

**Comment by cassiobotaro** [comment]
closed with #99
